### PR TITLE
Fix sync timer 401s

### PR DESCRIPTION
**Pull request by NicholasDenaro**

### CODE REVIEW

**Comment by CodePanter** [comment]
Hello there!
I assume you intended to make a pull request on your own project, and accidentally selected mine? This work looks really interesting regardless! Are you planning to make a pull request for the full feature set when you are done, or is your intent to use this privately?

**Comment by NicholasDenaro** [comment]
Hello.
Yes indeed I meant to merge into my fork, terribly sorry about that. Still not terribly used to GitHub's UX. I was debating on whether or not to make a pull request into this, but decided to submit my fork to the plugin hub. For the time being a group of friends and I are playing with this. If you wanted to collab instead of me submitting (yet another) bronzeman plugin I would be happy to do so and cancel my "new plugin" request.

**Comment by CodePanter** [comment]
I haven't had the chance to look at your code, but the feature sounds like something we should be able to implement without it getting in the way of solo players right? I personally also expect your plugin request to get feedback along the lines of them not wanting yet another bronzeman plugin, as there are three already.

**Comment by NicholasDenaro** [comment]
Yea, it shouldn't get in the way of solo-mode players, there's an option to sync and those can just be ignored. I've also added a bunch of quality of life options, like indicating which items are yours, marking natural spawns, and preventing pickup of items which are not yours.

**Comment by CodePanter** [comment]
That sounds really good! I think it would be wise to merge this into one plugin, instead of creating a fourth.

**Pull request closed without merging**
